// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/user.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FollowerIds          []int32    `protobuf:"varint,2,rep,packed,name=follower_ids,json=followerIds,proto3" json:"follower_ids,omitempty"`
	Info                 *User_Info `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_319252336e290d2b, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetFollowerIds() []int32 {
	if m != nil {
		return m.FollowerIds
	}
	return nil
}

func (m *User) GetInfo() *User_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

type User_Info struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Birthday             string   `protobuf:"bytes,2,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_Info) Reset()         { *m = User_Info{} }
func (m *User_Info) String() string { return proto.CompactTextString(m) }
func (*User_Info) ProtoMessage()    {}
func (*User_Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_319252336e290d2b, []int{0, 0}
}

func (m *User_Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Info.Unmarshal(m, b)
}
func (m *User_Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Info.Marshal(b, m, deterministic)
}
func (m *User_Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Info.Merge(m, src)
}
func (m *User_Info) XXX_Size() int {
	return xxx_messageInfo_User_Info.Size(m)
}
func (m *User_Info) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Info.DiscardUnknown(m)
}

var xxx_messageInfo_User_Info proto.InternalMessageInfo

func (m *User_Info) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User_Info) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

type GetUserRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_319252336e290d2b, []int{1}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_319252336e290d2b, []int{2}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "helloworld.User")
	proto.RegisterType((*User_Info)(nil), "helloworld.User.Info")
	proto.RegisterType((*GetUserRequest)(nil), "helloworld.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "helloworld.GetUserResponse")
}

func init() { proto.RegisterFile("src/user.proto", fileDescriptor_319252336e290d2b) }

var fileDescriptor_319252336e290d2b = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x69, 0xb7, 0xeb, 0x9f, 0x89, 0x54, 0x19, 0x10, 0x4a, 0xbd, 0xc4, 0xe2, 0xa1, 0x5e,
	0x2a, 0xd4, 0x83, 0x77, 0x11, 0x64, 0x8f, 0x46, 0x3c, 0xcb, 0x6e, 0x33, 0x65, 0x03, 0x35, 0xa9,
	0x49, 0x56, 0xf1, 0x4b, 0xf9, 0x19, 0x25, 0x71, 0x5d, 0x57, 0xd9, 0x5b, 0xde, 0xbc, 0x97, 0xdf,
	0x4b, 0x06, 0x72, 0x67, 0xbb, 0xab, 0x95, 0x23, 0xdb, 0x8c, 0xd6, 0x78, 0x83, 0xb0, 0xa4, 0x61,
	0x30, 0xef, 0xc6, 0x0e, 0xb2, 0xfa, 0x4c, 0x20, 0x7b, 0x72, 0x64, 0x11, 0x21, 0xd3, 0xf3, 0x17,
	0x2a, 0x12, 0x9e, 0xd4, 0x87, 0x22, 0x9e, 0xf1, 0x1c, 0x8e, 0x7a, 0x13, 0xa2, 0x64, 0x9f, 0x95,
	0x74, 0x45, 0xca, 0x27, 0xf5, 0x54, 0xb0, 0x9f, 0xd9, 0x4c, 0x3a, 0xbc, 0x84, 0x4c, 0xe9, 0xde,
	0x14, 0x13, 0x9e, 0xd4, 0xac, 0x3d, 0x6d, 0x7e, 0xd1, 0x4d, 0xc0, 0x36, 0x33, 0xdd, 0x1b, 0x11,
	0x23, 0xe5, 0x1d, 0x64, 0x41, 0x21, 0x07, 0x26, 0xc9, 0x75, 0x56, 0x8d, 0x5e, 0x19, 0xbd, 0x2e,
	0xdc, 0x1e, 0x61, 0x09, 0x07, 0x0b, 0x65, 0xfd, 0x52, 0xce, 0x3f, 0x8a, 0x34, 0xda, 0x1b, 0x5d,
	0x71, 0xc8, 0xef, 0xc9, 0x07, 0xb6, 0xa0, 0xd7, 0x15, 0x39, 0x8f, 0x39, 0xa4, 0x4a, 0x46, 0xcc,
	0x54, 0xa4, 0x4a, 0x56, 0x37, 0x70, 0xbc, 0x49, 0xb8, 0xd1, 0x68, 0x47, 0x78, 0x01, 0x59, 0xf8,
	0x7f, 0x0c, 0xb1, 0xf6, 0xe4, 0xff, 0x2b, 0x45, 0x74, 0xdb, 0x07, 0x60, 0x41, 0x3d, 0x92, 0x7d,
	0x53, 0x1d, 0xe1, 0x2d, 0xec, 0xaf, 0x39, 0x58, 0x6e, 0xdf, 0xf8, 0x5b, 0x5f, 0x9e, 0xed, 0xf4,
	0xbe, 0x8b, 0x17, 0x7b, 0x71, 0xe3, 0xd7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x87, 0x99, 0x74,
	0xcb, 0x83, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/helloworld.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/user.proto",
}
